version: '3.8'
services:
  mediamtx-srt:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx-srt
    restart: always
    ports:
      - "8554:8554"   # RTSP
      - "8888:8888"   # HLS
      - "1935:1935"   # RTMP
      - "9997:9997"   # API
      - "9998:9998"   # Metrics
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
      - ./hls:/hls
      - ./recordings:/recordings
  mediamtx-diskapi:
    build: ./mediamtx-diskapi
    container_name: mediamtx-diskapi
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - ./recordings:/recordings:ro
