authMethod: internal
authInternalUsers:
  - user: admin
    pass: adminpass
    ips: []
    permissions:
      - action: api
      - action: metrics
      - action: pprof
  - user: any
    pass:
    ips: []
    permissions:
      - action: publish
      - action: read

api: yes
apiAddress: :9997
metrics: yes
metricsAddress: :9998

rtspAddress: :8554
rtmpAddress: :1935
hlsAddress: :8888
webrtcAddress: :8889
srt: yes
srtAddress: :8890

paths:
  mystream:
    source: publisher
    sourceOnDemand: no
